config/routes.rb
Onlinebazar::Application.routes.draw do
  root :to => 'homes#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
  resources :categories do
    resources :products
  end
  resources :homes, :only => [:index]
  resources :events

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  validates :name, :presence => true
  # validates_uniqueness_of :name, :message => "%{value} has been taken"
  has_many :products, :dependent => :destroy
  has_many :sub_categories, :dependent => :destroy, :class_name => "Category", :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Category"
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :name, :event_type, :date, :description, :address, :address_latitude, :address_longitude, :address_locality, :address_country
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :image, :image_file_name, :image_file_type, :image_content_type, :image_file_size, :resource_type, :resource_id
  has_attached_file :image,
                    :styles => {:medium => "300x300>", :thumb => "100x100>"},
                    :url => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
  belongs_to :resource, :polymorphic => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :product_name, :price, :description, :image_updated_at, :pictures_attributes, :category_id
  has_many :pictures, :as => :resource, :dependent => :destroy
  belongs_to :category
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  # define_index do
  # 	indexes :product_name
  # end
  def self.search(search)
    if search
      find(:all, :conditions => ['product_name LIKE ? ', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :address, :address_latitude, :address_longitude, :address_locality, :address_country, :pictures_attributes
  has_many :pictures, :as => :resource, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :categories_displaying

  private
  def categories_displaying
  	@categories = Category.where(parent_id:nil)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.where(parent_id: nil)
	end
	def new
		@category = Category.new
		@categories = Category.where(parent_id:nil)
	end
	def show
		@category = Category.find(params[:id])
		@categories = Category.where(parent_id:nil)
	end
	def edit
		@category = Category.find(params[:id])
		@categories = Category.where(parent_id:nil)

	end
	def create
		@category = Category.new(params[:category])
		@categories = Category.where(parent_id:nil)
		if @category.save
			redirect_to category_path(@category)
		else
			render 'new'
		end
	end
	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(params[:category])
			redirect_to category_path(@category)
		else
			render 'index'
		end
	end
	def destroy
		@category = Category.find(params[:id])
		if @category.delete
			redirect_to :action => 'index'
		else
			render 'index'
		end
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end
	def new
		@event = Event.new
	end
	def show
		@event = Event.find(params[:id])
	end
	def edit
		@event = Event.find(params[:id])
	end
	def create
		@event = Event.new(params[:event])
		if @event.save
			redirect_to event_path(@event)
		else
			render 'new'
		end
	end
	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(params[:event])
			redirect_to event_path(@event)
		else
			render 'index'
		end
	end
	def destroy
		@event = Event.find(params[:id])
		if @event.delete
			redirect_to :action => "index"
		else
			render 'index'
		end
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.search(params[:search])
	end
	def show
		# debugger
		# @categories = Category.where(parent_id:nil)
		@product = Product.find(params[:id])
	end
	def new
		@categories = Category.all
		@product = Product.new
	end
	def edit
		@product = Product.find(params[:id])
	end
	def create
		@categories = Category.where(parent_id:nil)
		@product = Product.new(params[:product])
		# debugger
		if @product.save
			redirect_to category_products_path(@categories)
		else
			render 'new'
		end
	end
	def update
		@categories = Category.where(parent_id:nil)
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to product_path(@product)
		else
			render 'edit'
		end
	end
	def destroy
		@product = Product.find(params[:id])
		if @product.delete
			redirect_to product_path(@product)
		else
			render 'index'
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_edit_form.html.haml
= form_for @category do |f|
  - @category.errors.full_messages.each do |error|
    = error

  = f.label :parent
  = f.select("parent_id", @categories.collect{|p| [ p.name, p.id ]}, { :include_blank => "Select Category")}

  = f.label :name
  = f.text_field :name

  = f.submit

app/views/categories/_form.html.haml
.category_form
  %h2 Category
  .form-horizontal.category_page{role: "form"}
    = form_for @category do |f|
      - @category.errors.full_messages.each do |error|
        = error
      .form-group
        = f.label :parent_category
        .col-sm-10
          = f.select("parent_id", @categories.collect{|p| [ p.name, p.id ] }, {:include_blank => 'Select category'})
      .form-group
        = f.label :name
        .col-sm-10
          = f.text_field :name
      .form-group
        .col-sm-10
          = f.submit "save", :class => "btn btn-default"

app/views/categories/edit.html.haml
= render :partial => 'edit_form'

app/views/categories/edit.js.haml
$("#edit_form").html("#{escape_javascript(render :partial => 'edit_form')}");

app/views/categories/index.html.haml
%h1 Categories
%table.table.table-striped
  %thead
    %tr
      %th Name
  %tbody
    - @categories.each do |category|
      %tr
        %td 
          = category.name
          = link_to "Destroy", category, :method => :delete, :confirm => "Are you sure", :class => "btn btn-min btn-danger"
          = link_to "Edit", edit_category_path(category), :class => 'btn btn-mini',:remote => true
          - category.sub_categories.each do |subcategory|
            %td 
              = subcategory.name
              = link_to "Destroy", category_path(subcategory), :method => :delete, :confirm => "Are you sure", :class => "btn btn-min btn-danger"
              = link_to "Edit", edit_category_path(category), :class => 'btn btn-mini',:remote => true

= link_to "Add Category", new_category_path, :class => "btn btn-primary"
#edit_form

app/views/categories/new.html.haml
= render :partial => 'form'

app/views/categories/show.html.haml
.category_show
  %h2 Category Show
  .category_page
    .form-group
      .col-sm-10
        %li
          = @category.name
    = link_to "Back to Index", categories_path, :class => "btn btn-default"
    = link_to "Add Product", new_category_product_path(@category), :class => "btn btn-default"

app/views/events/_form.html.haml
%form#components.form-horizontal
  = form_for @event do |f|
    %fieldset
      .tab-content
        //Tabs of snippets go here
	      #input.tab-pane.active
	        .component
            / Text input
            .control-group
              %label.control-label
                = f.label :name, :for => "textinput"
              .controls
                %input#textinput.input-xlarge
                  = f.text_field :name, :placeholder => "insert event name", :name => "textinput", :type => "text"
                %p.help-block help
          .component
            / Button Drop Down
            .control-group
              %label.control-label
                = f.label :event_type, :for => "buttondropdown"
              .controls
                .input-append
                  %input#buttondropdown.input-xlarge
                    = f.select :event_type, :name => "buttondropdown", :placeholder => "please select any event type", :type => "text"
                  .btn-group
                    %button.btn.dropdown-toggle{"data-toggle" => "dropdown"}
                      Event Type
                      %span.caret
                    %ul.dropdown-menu
                      %li
                        %a{href: "#"} Business
                      %li
                        %a{href: "#"} Technology
                      %li
                        %a{href: "#"} Social Networking
          .component
            / Search input
            .control-group
              %label.control-label{for: "searchinput"} Search Input
                = f.label :date, :for => "date_select"
              .controls
                %input#searchinput.input-xlarge.search-query
                  = f.datepicker :date, :name => "date_select", :type => "text"
                %p.help-block help
	        .component
	          / Prepended text
	          .control-group
	            %label.control-label{for: "prependedtext"} Prepended Text
	            .controls
	              .input-prepend
	                %span.add-on prepend
	                %input#prependedtext.input-xlarge{name: "prependedtext", placeholder: "placeholder", type: "text"}/
	              %p.help-block help
	        .component
	          / Appended Input
	          .control-group
	            %label.control-label{for: "appendedtext"} Appended Text
	            .controls
	              .input-append
	                %input#appendedtext.input-xlarge{name: "appendedtext", placeholder: "placeholder", type: "text"}/
	                %span.add-on append
	              %p.help-block help
	        .component
	          / Prepended checkbox
	          .control-group
	            %label.control-label{for: "prependedcheckbox"} Prepended Checkbox
	            .controls
	              .input-prepend
	                %span.add-on
	                  %label.checkbox
	                    %input{type: "checkbox"}/
	                %input#prependedcheckbox.input-xlarge{name: "prependedcheckbox", placeholder: "placeholder", type: "text"}/
	              %p.help-block help
	        .component
	          / Appended checkbox
	          .control-group
	            %label.control-label{for: "appendedcheckbox"} Appended Checkbox
	            .controls
	              .input-append
	                %input#appendedcheckbox.span2{name: "appendedcheckbox", placeholder: "placeholder", type: "text"}/
	                %span.add-on
	                  %input{type: "checkbox"}/
	              %p.help-block help
	        .component
	          / Textarea
	          .control-group
	            %label.control-label{for: "textarea"} Text Area
	            .controls
	              %textarea#textarea{name: "textarea"} default text
	      
      

app/views/events/index.html.haml
= link_to "Add Event", new_event_path

app/views/events/new.html.haml
= render :partial => "form"

app/views/homes/_index.html.haml
%body.main_page
  .container
    / Carousel
    /
      consult Bootstrap docs at
      http://twitter.github.com/bootstrap/javascript.html#carousel
    #this-carousel-id.carousel.slide
      .carousel-inner
        .item
          %a{href: "http://hubblesite.org/gallery/album/entire/pr2006046a/xlarge_web/npp/128/"}
            = image_tag "ngc5866.jpg"
          .carousel-caption
            %p The Antennae Galaxies
            %p
              %a{href: "http://hubblesite.org/gallery/album/entire/pr2006046a/xlarge_web/npp/128/"} Hubblesite.org »
        .item
          %a{href: "http://hubblesite.org/gallery/album/entire/pr2007016e/xlarge_web/npp/128/"}
            = image_tag "echo.jpg"
          .carousel-caption
            %p Carina Nebula: The Caterpillar
            %p
              %a{href: "http://hubblesite.org/gallery/album/entire/pr2007016e/xlarge_web/npp/128/"} Hubblesite.org »
        .item.active
          %a{href: "http://hubblesite.org/gallery/album/entire/pr2003010i/npp/128/"}
            = image_tag "carina.jpg"
          .carousel-caption
            %p Light Echo From Star V838 Monocerotis
            %p
              %a{href: "http://hubblesite.org/gallery/album/entire/pr2003010i/npp/128/"} Hubblesite.org »
        .item
          %a{href: "http://hubblesite.org/gallery/album/entire/pr2006024a/xlarge_web/npp/128/"}
            = image_tag "antennae.jpg"
          .carousel-caption
            %p Galaxy NGC 5866
            %p
              %a{href: "http://hubblesite.org/gallery/album/entire/pr2006024a/xlarge_web/npp/128/"} Hubblesite.org »
      / .carousel-inner
      /
        next and previous controls here
        href values must reference the id for this carousel
      %a.carousel-control.left{"data-slide" => "prev", href: "#this-carousel-id"} ‹
      %a.carousel-control.right{"data-slide" => "next", href: "#this-carousel-id"} ›
    / .carousel
    / end carousel
    / Example row of columns
    .row
      .span4
        %h2 Heading
        %p
          Donec id elit non mi porta gravida at eget metus. Fusce
          dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut
          fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
          mollis euismod. Donec sed odio dui.
        %p
          %a.btn{href: "#"} View details »
      .span4
        %h2 Heading
        %p
          Donec id elit non mi porta gravida at eget metus. Fusce
          dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut
          fermentum massa justo sit amet risus. Etiam porta sem malesuada magna
          mollis euismod. Donec sed odio dui.
        %p
          %a.btn{href: "#"} View details »
      .span4
        %h2 Heading
        %p
          Donec sed odio dui. Cras justo odio, dapibus ac facilisis
          in, egestas eget quam. Vestibulum id ligula porta felis euismod semper.
          Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
          ut fermentum massa justo sit amet risus.
        %p
          %a.btn{href: "#"} View details »
    %hr/
    %footer
      %p
        By
        %a{href: "http://twitter.com/davidcochran"} David Cochran
        of
        %a{href: "http://alittlecode.com/"} aLittleCode.com
        for
        %a{href: "http://webdesign.tutsplus.com/"} webdesign.tutsplus.com
  / /container
  /
    Le javascript
    \==================================================
  / Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary
  %script{src: "Carousel%20%7C%20Twitter%20Bootstrap%202.0.4_files/jquery.js"}
  :javascript
    window.jQuery || document.write('<script src="js/jquery-1.7.2.min.js"><\/script>')
  / Bootstrap jQuery plugins compiled and minified
  %script{src: "Carousel%20%7C%20Twitter%20Bootstrap%202.0.4_files/bootstrap.js"}
  :javascript
    $(document).ready(function(){
      $('.carousel').carousel({
        interval: 4000
      });
    });

app/views/homes/_main_navigation.html.haml
%nav.navbar.navbar-inverse{role: "navigation"}
  .navbar-header
    %ul.nav.navbar-nav
      - @categories.each do |category|
        %li.dropdown.active
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = category.name
          %ul.dropdown-menu
            - category.sub_categories.each do |subcategory|
              %li
                %a
                  = link_to "#{subcategory.name}", category_products_path(@categories)
  / /.navbar-collapse

app/views/homes/_my_account.html.haml
%div{style: "float: right;margin-right: 23px;"}
  - if user_signed_in?
    = current_user.email
    = link_to "Categories", categories_path, :class => 'btn btn-primary'
    = link_to "Products", category_products_path(@categories), :class => 'btn btn-primary'
    = link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary'
  - else
    = link_to "Sign up", new_user_registration_path, :class => "btn pull-right"
    = link_to "Sign in", new_user_session_path, :class => "btn pull-right"

app/views/homes/index.html.haml
= render :partial => "index"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Onlinebazar
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.main_page{style: "background: #EEEEEE;"}
    %div
      .navbar.navbar-fixed-top
        .navbar-inner
          .container.header
            %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            .header_main_text
              = link_to (image_tag "main_text.gif"), root_path
            .nav-collapse
              %ul.nav
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                    User
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      %a{href: "#"} Profile
                    %li
                      %a{href: "#"} Setting
                    %li
                      %a{href: "#"} Event
                / dropdown
                = render :partial => "/homes/my_account"
                // Main Navigatio
                = render :partial => "/homes/main_navigation"
              / /.nav
            / /.nav-collapse
          / /.container
        / /.navbar-inner
      / /.navbar
    = yield

app/views/products/_form.html.haml
.product_form
  %h1 Product
  = nested_form_for([@category,@product], :url => category_products_url, :html => {:multiple => true}) do |f|
    - @product.errors.full_messages.each do |error|
      = error
    .field
      = f.label :category
      = f.select :category_id, options_for_select(@categories.map{|i| [i.name, i.id]})
    .field
      = f.label :product_name
      = f.text_field :product_name
    .field
      - f.fields_for :pictures do |photo|
        %p
          = photo.label :image
          = photo.file_field :image
          = photo.link_to_remove "Remove This Photo", :class => 'btn btn-danger'
      = f.link_to_add "Add a image", :pictures, :class => 'btn btn-primary'
    .field
      = f.label :price
      = f.text_field :price
    .field
      = f.label :description
      = f.text_area :description, :cols => 50, :rows => 5
    .field
      = f.submit "Create", :class => "btn btn-primary"

app/views/products/_product_details.html.haml
.product_show
  = @product.product_name
  - @product.pictures.each do |photo|
    = image_tag photo.image(:thumb)
  = @product.price
  = @product.description
  = link_to "Index", category_products_path(@category)

app/views/products/edit.html.haml
= render :partial => 'new'

app/views/products/index.html.haml
.form-horizontal.products_page{role: "form"}
  .row
    - @products.each do |product|
      .col-sm-6.col-md-4
        %a.thumbnail
          - product.pictures.each do |photo|
            = image_tag photo.image(:thumb)
          .caption
            %p
              = product.product_name
            %p
              = product.price
            %p
              = product.description
            %p
              =# @categories.name
          = #link_to "Destroy", [@category, product], :method => :delete, :confirm => "Are you sure", :class => "btn btn-min btn-danger"
          = #link_to "Edit", edit_category_product(@category,product), :class => 'btn btn-mini',:remote => true
  = form_tag category_products_path, :method => 'get' do
    = text_field_tag :search, params[:search], :placeholder => "search products"
  = link_to "Add Product", new_category_product_path(@categories), :class => "btn btn-default add_product"

app/views/products/new.html.haml
= render :partial => 'form'

app/views/products/show.html.haml
= render :partial => "product_details"